### ISSUE TITLE
Transfer to gogoair?

### ISSUE THREAD

**Issue by MilosRasic** [gogoair/react-combo-select#10]
Are we doing this?

Here's a guide https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

You should still have the necessary permissions on https://github.com/gogoair

Don't know how else to contact you :)

Also don't forget react-combo-modal

**Comment by markokostovski** [comment]
Roger, roger, just give me exact account name on which to transfer and my child will be given :D

**Comment by MilosRasic** [comment]
https://github.com/gogoair

**Comment by markokostovski** [comment]
"Cannot find new owner 'https://github.com/gogoair'", I will transfer it to you, and you can transfer it to gogo

**Comment by markokostovski** [comment]
Transfered to Vida, she will continue
